// SPDX-License-Identifier: GPL-3.0-only
package ca.terradevop.openodo.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import ca.terradevop.openodo.core.model.*
import ca.terradevop.openodo.core.money.Money
import ca.terradevop.openodo.core.reminders.DueCalculator
import ca.terradevop.openodo.core.reminders.ReminderState
import ca.terradevop.openodo.core.units.*
import java.time.LocalDate

private enum class Destination(val label: String) { VEHICLES("Vehicles"), DASHBOARD("Dashboard"), RECORDS("Records"), REMINDERS("Reminders"), SETTINGS("Settings") }

@Composable
fun OpenOdoApp(viewModel: AppViewModel) {
    val state by viewModel.state.collectAsState()
    var destination by remember { mutableStateOf(Destination.DASHBOARD) }
    var action by remember { mutableStateOf<String?>(null) }
    Scaffold(bottomBar = { NavigationBar { Destination.entries.forEach { item -> NavigationBarItem(destination == item, { destination = item; action = null }, icon = { Text(item.label.take(1), fontWeight = FontWeight.Bold) }, label = { Text(item.label) }) } } }) { padding ->
        when (destination) {
            Destination.VEHICLES -> VehiclesScreen(state, viewModel, Modifier.padding(padding))
            Destination.DASHBOARD -> DashboardScreen(state, viewModel, Modifier.padding(padding), { destination = Destination.RECORDS; action = "fuel" }, { destination = Destination.RECORDS; action = "expense" }, { destination = Destination.REMINDERS; action = "reminder" })
            Destination.RECORDS -> RecordsScreen(state, viewModel, Modifier.padding(padding), action) { action = null }
            Destination.REMINDERS -> RemindersScreen(state, viewModel, Modifier.padding(padding), action == "reminder") { action = null }
            Destination.SETTINGS -> SettingsScreen(state, Modifier.padding(padding))
        }
    }
}

@Composable private fun Frame(title: String, modifier: Modifier, action: (@Composable () -> Unit)? = null, content: @Composable () -> Unit) { Column(modifier.fillMaxSize()) { Row(Modifier.fillMaxWidth().padding(20.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text("OPENODO", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary, fontWeight = FontWeight.Bold); Text(title, style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold) }; action?.invoke() }; content() } }
@Composable private fun VehiclesScreen(state: ShellState, viewModel: AppViewModel, modifier: Modifier) { var form by remember { mutableStateOf(false) }; if (form) { VehicleForm({ viewModel.save(it); form = false }, { form = false }, modifier); return }; Frame("Vehicles", modifier, { TextButton({ form = true }) { Text("+ Add vehicle") } }) { LazyColumn(Modifier.padding(horizontal = 20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { if (state.vehicles.isEmpty()) item { EmptyCard("Your garage is empty", "Add your first vehicle to start.", "Add vehicle") { form = true } }; items(state.vehicles, key = { it.id }) { v -> VehicleCard(v, state.activeVehicleId == v.id) { viewModel.select(v.id) } }; if (state.archivedVehicles.isNotEmpty()) { item { Text("Archived", style = MaterialTheme.typography.titleMedium) }; items(state.archivedVehicles, key = { it.id }) { VehicleCard(it, false) {} } } } } }
@Composable private fun VehicleCard(v: Vehicle, active: Boolean, onClick: () -> Unit) { Card(onClick = onClick, Modifier.fillMaxWidth(), border = androidx.compose.foundation.BorderStroke(if (active) 2.dp else 1.dp, if (active) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.outlineVariant)) { Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) { Row { Text(v.name, Modifier.weight(1f), fontWeight = FontWeight.Bold); if (active) Pill("ACTIVE", MaterialTheme.colorScheme.primaryContainer, MaterialTheme.colorScheme.onPrimaryContainer) }; Text("${v.make} ${v.model} • ${v.year}", style = MaterialTheme.typography.bodySmall); Text("${v.distanceUnit.name} • ${v.volumeUnit.name} • ${v.energyUnit.name} • ${v.currency}", style = MaterialTheme.typography.labelSmall) } } }
@Composable private fun DashboardScreen(state: ShellState, viewModel: AppViewModel, modifier: Modifier, fuel: () -> Unit, expense: () -> Unit, reminder: () -> Unit) { val v = state.vehicles.firstOrNull { it.id == state.activeVehicleId }; Frame(v?.name ?: "Dashboard", modifier, { v?.let { Pill(it.currency, MaterialTheme.colorScheme.secondaryContainer, MaterialTheme.colorScheme.onSecondaryContainer) } }) { if (v == null) EmptyCard("Set up your first vehicle", "OpenOdo keeps your log on this device.", null, null) else LazyColumn(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) { item { Card(Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primary)) { Column(Modifier.padding(20.dp)) { Text("CURRENT READING", color = MaterialTheme.colorScheme.onPrimary, style = MaterialTheme.typography.labelSmall); Text(v.manualOdometer?.value?.toString() ?: "—", color = MaterialTheme.colorScheme.onPrimary, style = MaterialTheme.typography.displayMedium, fontWeight = FontWeight.Bold); Text(v.distanceUnit.name, color = MaterialTheme.colorScheme.onPrimary) } } }; item { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(fuel, Modifier.weight(1f)) { Text("Fuel") }; OutlinedButton(expense, Modifier.weight(1f)) { Text("Expense") }; OutlinedButton(reminder, Modifier.weight(1f)) { Text("Reminder") } } }; item { Text("Recent activity", style = MaterialTheme.typography.titleMedium) } } } }
@Composable private fun RecordsScreen(state: ShellState, vm: AppViewModel, modifier: Modifier, action: String?, clear: () -> Unit) { val v = state.vehicles.firstOrNull { it.id == state.activeVehicleId }; var mode by remember { mutableIntStateOf(0) }; var addFuel by remember(action) { mutableStateOf(action == "fuel") }; var addExpense by remember(action) { mutableStateOf(action == "expense") }; LaunchedEffect(action) { if (action != null) clear() }; if (v != null && addFuel) { FuelForm(v, { vm.saveFuel(it); addFuel = false }, { addFuel = false }, modifier); return }; if (v != null && addExpense) { ExpenseForm(v, vm, { vm.saveExpense(it); addExpense = false }, { addExpense = false }, modifier); return }; val fuels = v?.let { vm.fuelEntries(it.id).collectAsState(initial = emptyList()).value }; val expenses = v?.let { vm.expenseRecords(it.id).collectAsState(initial = emptyList()).value }; Frame("Records", modifier, { TextButton({ if (mode == 0) addFuel = true else addExpense = true }) { Text("+ Add") } }) { Column(Modifier.padding(20.dp)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { FilterChip(mode == 0, { mode = 0 }, label = { Text("Fuel") }); FilterChip(mode == 1, { mode = 1 }, label = { Text("Expenses") }) }; Spacer(Modifier.height(12.dp)); if (mode == 0) { if (fuels.isNullOrEmpty()) EmptyCard("No fuel history", "Log your first fill-up.", "Add fuel") { addFuel = true } else LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { items(fuels, key = { it.id }) { FuelCard(it) } } } else { if (expenses.isNullOrEmpty()) EmptyCard("No expenses", "Log your first service record.", "Add expense") { addExpense = true } else LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { items(expenses, key = { it.id }) { ExpenseCard(it) } } } } } }
@Composable private fun RemindersScreen(state: ShellState, vm: AppViewModel, modifier: Modifier, open: Boolean, clear: () -> Unit) { val v = state.vehicles.firstOrNull { it.id == state.activeVehicleId }; var form by remember(open) { mutableStateOf(open) }; LaunchedEffect(open) { if (open) clear() }; if (v != null && form) { ReminderForm(v, vm, { vm.saveReminder(it); form = false }, { form = false }, modifier); return }; val rs = if (v == null) emptyList<Reminder>() else vm.reminders(v.id).collectAsState(initial = emptyList()).value; Frame("Reminders", modifier, { TextButton({ form = true }) { Text("+ Add") } }) { LazyColumn(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Text("Whichever interval comes first", style = MaterialTheme.typography.bodySmall) }; if (rs.isEmpty()) item { EmptyCard("No reminders", "Add a service interval.", "Add reminder") { form = true } }; if (v != null) items(rs, key = { it.id }) { ReminderCard(it, v, vm) } } } }
@Composable private fun SettingsScreen(state: ShellState, modifier: Modifier) { Frame("Settings", modifier) { LazyColumn(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { SettingsCard("Active vehicle", state.vehicles.firstOrNull { it.id == state.activeVehicleId }?.currency ?: "No vehicle") }; item { SettingsCard("Backup & migration", "JSON • CSV • Drivvo • Fuelio") }; item { SettingsCard("Privacy", "Offline-first • zero tracking") } } } }
@Composable private fun VehicleForm(save: (Vehicle) -> Unit, cancel: () -> Unit, modifier: Modifier) { var name by remember { mutableStateOf("") }; Column(modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Text("Add vehicle", style = MaterialTheme.typography.headlineSmall); OutlinedTextField(name, { name = it }, Modifier.fillMaxWidth(), label = { Text("Vehicle name") }); Row { OutlinedButton(cancel) { Text("Cancel") }; Spacer(Modifier.width(8.dp)); Button({ save(Vehicle(name = name, make = "", model = "", year = 2024, vin = null, photoFileName = null, distanceUnit = DistanceUnit.KILOMETRES, volumeUnit = VolumeUnit.LITRES, energyUnit = EnergyUnit.KILOWATT_HOURS, currency = "USD", manualOdometer = null, manualOdometerAt = null, isArchived = false, notes = null, createdAt = 0, updatedAt = 0)) }, enabled = name.isNotBlank()) { Text("Save") } } } }
@Composable private fun FuelForm(v: Vehicle, save: (FuelEntry) -> Unit, cancel: () -> Unit, modifier: Modifier) {
    var amount by remember { mutableStateOf("") }; var cost by remember { mutableStateOf("") }; var odo by remember { mutableStateOf("") }; var label by remember { mutableStateOf("") }; var error by remember { mutableStateOf<String?>(null) }
    Column(modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
        Text("Add fuel", style = MaterialTheme.typography.headlineSmall)
        OutlinedTextField(odo, { odo = it }, Modifier.fillMaxWidth(), label = { Text("Odometer (${v.distanceUnit.name})") }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number))
        OutlinedTextField(amount, { amount = it }, Modifier.fillMaxWidth(), label = { Text("Volume (${v.volumeUnit.name})") }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number))
        OutlinedTextField(cost, { cost = it }, Modifier.fillMaxWidth(), label = { Text("Cost (${v.currency})") }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number))
        OutlinedTextField(label, { label = it }, Modifier.fillMaxWidth(), label = { Text("Fuel label") })
        error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
        Row { OutlinedButton(cancel) { Text("Cancel") }; Spacer(Modifier.width(8.dp)); Button({ val a = amount.toLongOrNull(); val c = cost.toLongOrNull(); val o = odo.toLongOrNull(); if (a == null || a <= 0 || c == null || c < 0 || o == null || o < 0 || label.isBlank()) error = "Odometer, label, positive volume, and non-negative cost are required" else save(FuelEntry(vehicleId = v.id, date = LocalDate.now(), odometer = Metres(o * 1_000), kind = FuelKind.LIQUID, volume = Millilitres(a * 1_000), energy = null, unitPrice = null, totalCost = Money(c * 100, v.currency), fuelLabel = label, fullTank = true, missedPreviousFillUp = false, stationName = null, receiptFileName = null, notes = null, createdAt = System.currentTimeMillis(), updatedAt = System.currentTimeMillis())) }) { Text("Save") } }
    }
}
@Composable private fun ExpenseForm(v: Vehicle, vm: AppViewModel, save: (ExpenseRecord) -> Unit, cancel: () -> Unit, modifier: Modifier) { var title by remember { mutableStateOf("") }; var cost by remember { mutableStateOf("") }; var odo by remember { mutableStateOf("") }; val types = vm.recordTypes().collectAsState(initial = emptyList()).value; var type by remember { mutableStateOf(types.firstOrNull()?.id ?: 0) }; var error by remember { mutableStateOf<String?>(null) }; Column(modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Text("Add expense", style = MaterialTheme.typography.headlineSmall); LazyColumn(Modifier.heightIn(max = 100.dp)) { items(types) { t -> FilterChip(type == t.id, { type = t.id }, label = { Text(t.name) }) } }; OutlinedTextField(title, { title = it }, Modifier.fillMaxWidth(), label = { Text("Title") }); OutlinedTextField(odo, { odo = it }, Modifier.fillMaxWidth(), label = { Text("Odometer (${v.distanceUnit.name})") }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)); OutlinedTextField(cost, { cost = it }, Modifier.fillMaxWidth(), label = { Text("Cost (${v.currency})") }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)); error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; Row { OutlinedButton(cancel) { Text("Cancel") }; Spacer(Modifier.width(8.dp)); Button({ val c = cost.toLongOrNull(); val o = odo.toLongOrNull(); if (type == 0L || title.isBlank() || c == null || c < 0 || o == null || o < 0) error = "Choose a type and enter title, odometer, and non-negative cost" else save(ExpenseRecord(vehicleId = v.id, typeId = type, date = LocalDate.now(), odometer = Metres(o * 1_000), title = title, description = null, cost = Money(c * 100, v.currency), performedBy = PerformedBy.SELF, shopName = null, warrantyUntil = null, receiptFileName = null, notes = null, createdAt = System.currentTimeMillis(), updatedAt = System.currentTimeMillis())) }) { Text("Save") } } } }
@Composable private fun ReminderForm(v: Vehicle, vm: AppViewModel, save: (Reminder) -> Unit, cancel: () -> Unit, modifier: Modifier) { val types = vm.recordTypes().collectAsState(initial = emptyList()).value.filter { it.category == RecordCategory.SERVICE }; var type by remember { mutableStateOf(types.firstOrNull()?.id ?: 0) }; var months by remember { mutableStateOf("") }; Column(modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Text("Add reminder", style = MaterialTheme.typography.headlineSmall); LazyColumn(Modifier.heightIn(max = 120.dp)) { items(types) { t -> FilterChip(type == t.id, { type = t.id }, label = { Text(t.name) }) } }; OutlinedTextField(months, { months = it }, Modifier.fillMaxWidth(), label = { Text("Interval months") }); Row { OutlinedButton(cancel) { Text("Cancel") }; Spacer(Modifier.width(8.dp)); Button({ save(Reminder(vehicleId = v.id, typeId = type, intervalDistance = null, intervalMonths = months.toIntOrNull(), anchorDate = null, anchorOdometer = null, active = true)) }) { Text("Save") } } } }
@Composable private fun FuelCard(f: FuelEntry) { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) { Text(f.fuelLabel, fontWeight = FontWeight.Bold); Text("${f.date} • ${f.totalCost.currency} ${f.totalCost.minor}", style = MaterialTheme.typography.bodySmall) } } }
@Composable private fun ExpenseCard(r: ExpenseRecord) { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) { Text(r.title, fontWeight = FontWeight.Bold); Text("${r.date} • ${r.cost.currency} ${r.cost.minor}", style = MaterialTheme.typography.bodySmall) } } }
@Composable private fun ReminderCard(r: Reminder, v: Vehicle, vm: AppViewModel) { val s = DueCalculator.evaluate(r, v.manualOdometer, LocalDate.now()); Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) { Row { Text("Service #${r.typeId}", Modifier.weight(1f), fontWeight = FontWeight.Bold); Pill(s.state.name, MaterialTheme.colorScheme.primaryContainer, MaterialTheme.colorScheme.onPrimaryContainer) }; Text("Due ${s.nextDueDate ?: "after matching service"}", style = MaterialTheme.typography.bodySmall); TextButton({ vm.saveReminder(r.copy(anchorDate = LocalDate.now(), anchorOdometer = v.manualOdometer)) }) { Text("Manual reset") } } } }
@Composable private fun QuickActions(f: () -> Unit, e: () -> Unit, r: () -> Unit) { Row(Modifier.fillMaxWidth(), Arrangement.spacedBy(8.dp)) { Button(f, Modifier.weight(1f)) { Text("Fuel") }; OutlinedButton(e, Modifier.weight(1f)) { Text("Expense") }; OutlinedButton(r, Modifier.weight(1f)) { Text("Reminder") } } }
@Composable private fun SmallAction(mark: String, label: String, click: () -> Unit) { TextButton(click) { Text("$mark $label") } }
@Composable private fun SectionLabel(t: String) { Text(t.uppercase(), style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant, fontWeight = FontWeight.Bold) }
@Composable private fun ConfigPill(t: String) { Surface(color = MaterialTheme.colorScheme.secondaryContainer, shape = RoundedCornerShape(8.dp)) { Text(t, Modifier.padding(7.dp), style = MaterialTheme.typography.labelSmall) } }
@Composable private fun Pill(t: String, bg: Color, fg: Color) { Surface(color = bg, shape = RoundedCornerShape(50)) { Text(t, Modifier.padding(8.dp), color = fg, style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold) } }
@Composable private fun EmptyCard(title: String, message: String, action: String? = null, click: (() -> Unit)? = null) { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(18.dp)) { Text(title, fontWeight = FontWeight.Bold); Text(message, style = MaterialTheme.typography.bodySmall); if (action != null && click != null) Button(click) { Text(action) } } } }
@Composable private fun SettingsCard(t: String, d: String) { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text(t, fontWeight = FontWeight.Bold); Text(d, style = MaterialTheme.typography.bodySmall) } } }
