// SPDX-License-Identifier: GPL-3.0-only
package ca.cyberengma.openodo.core.model

object DefaultRecordTypes {
    val all: List<RecordType> = listOf(
        RecordType(category = RecordCategory.SERVICE, name = "oil change", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "oil filter", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "air filter", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "cabin filter", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "brake pads", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "brake fluid", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "tire rotation", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "wheel alignment", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "coolant", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "spark plugs", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "transmission fluid", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "timing belt", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "battery", isDefault = true),
        RecordType(category = RecordCategory.SERVICE, name = "general inspection", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "engine", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "transmission", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "electrical", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "body", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "suspension", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "exhaust", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "cooling", isDefault = true),
        RecordType(category = RecordCategory.REPAIR, name = "other", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "wheels & tires", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "suspension", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "exhaust", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "brakes", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "audio", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "lighting", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "body kit", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "performance", isDefault = true),
        RecordType(category = RecordCategory.UPGRADE, name = "other", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "insurance", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "registration", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "inspection fee", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "parking", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "tolls", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "fine", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "wash", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "accessories", isDefault = true),
        RecordType(category = RecordCategory.OTHER, name = "other", isDefault = true),
    )
}
